import type { Metadata } from "next";
import { Sora, Russo_One } from "next/font/google";
import "./globals.css";
const soraSansSerif = Sora({
	variable: "--font-sora",
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800"],
	display: "swap",
});

const russoOneSansSerif = Russo_One({
	variable: "--font-russo",
	subsets: ["latin"],
	weight: "400",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${soraSansSerif.variable} ${russoOneSansSerif.variable} antialiased`}>{children}</body>
		</html>
	);
}
