name: NextJsPortfolio

on:
    push:
        branches: ["main"]
        paths:
            - "**.js"
            - "**.ts"
            - "**.tsx"
            - "package.json"
            - "tsconfig.json"
            - "next.config.*"
            - "tailwind.config.*"

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
              with:
                  clean: false
                  fetch-depth: 0

    server:
        needs: build
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Cache node modules + Next.js build cache
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      .next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-

            - name: Install Node Modules
              run: npm ci

            - name: Build the code
              run: npm run build

            - name: Start or Reload PM2 Process
              run: |
                  if pm2 list | grep -q "nextjsportfolio"; then
                    echo "Reloading existing PM2 process..."
                    pm2 reload nextjsportfolio --update-env
                  else
                    echo "Starting new PM2 process"
                    pm2 start npm --name nextjsportfolio -- start --time
                  fi
