name: NextJsPortfolio

on:
    push:
        branches: ["main"]
        paths:
            - "**.js"
            - "**.ts"
            - "**.tsx"
            - "package.json"
            - "tsconfig.json"
            - "next.config.*"
            - "tailwind.config.*"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Store current package-lock.json hash
              id: current-package-lock-hash
              run: echo "hash=$(sha256sum package-lock.json | awk '{print $1}')" >> $GITHUB_OUTPUT

            - name: Create .env file
              run: echo "${{ secrets.PRODUCTION_ENV }}" > .env

            - name: Checkout the code
              uses: actions/checkout@v4
              with:
                  clean: false
                  fetch-depth: 0

            - name: Compare latest package-lock.json hash with previous hash
              id: compare-hashes
              run: |
                  NEW_HASH=$(sha256sum package-lock.json | awk '{ print $1 }')
                  if [ "$NEW_HASH" != "${{ steps.current-package-lock-hash.outputs.hash }}" ]; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Install Node Modules
              if: steps.compare-hashes.outputs.changed == 'true'
              run: npm ci

            - name: Build the code
              run: npm run build

            - name: Start or Reload PM2 Process
              run: |
                  if pm2 list | grep -q "nextjsportfolio"; then
                    echo "Reloading existing PM2 process..."
                    pm2 reload nextjsportfolio --update-env
                  else
                    echo "Starting new PM2 process"
                    pm2 start npm --name nextjsportfolio -- start --time
                  fi
                  pm2 save
